#line 2 "tokens.cpp"

#line 4 "tokens.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ic__create_buffer
#define yy_delete_buffer ic__delete_buffer
#define yy_flex_debug ic__flex_debug
#define yy_init_buffer ic__init_buffer
#define yy_flush_buffer ic__flush_buffer
#define yy_load_buffer_state ic__load_buffer_state
#define yy_switch_to_buffer ic__switch_to_buffer
#define yyin ic_in
#define yyleng ic_leng
#define yylex ic_lex
#define yylineno ic_lineno
#define yyout ic_out
#define yyrestart ic_restart
#define yytext ic_text
#define yywrap ic_wrap
#define yyalloc ic_alloc
#define yyrealloc ic_realloc
#define yyfree ic_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ic_restart(ic_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t ic_leng;

extern FILE *ic_in, *ic_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ic_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ic_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ic_restart()), so that the user can continue scanning by
	 * just pointing ic_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ic_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t ic_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ic_wrap()'s to do buffer switches
 * instead of setting up a fresh ic_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ic_restart (FILE *input_file  );
void ic__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ic__create_buffer (FILE *file,int size  );
void ic__delete_buffer (YY_BUFFER_STATE b  );
void ic__flush_buffer (YY_BUFFER_STATE b  );
void ic_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void ic_pop_buffer_state (void );

static void ic_ensure_buffer_stack (void );
static void ic__load_buffer_state (void );
static void ic__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ic__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ic__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ic__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ic__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *ic_alloc (yy_size_t  );
void *ic_realloc (void *,yy_size_t  );
void ic_free (void *  );

#define yy_new_buffer ic__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ic_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ic__create_buffer(ic_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ic_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ic__create_buffer(ic_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *ic_in = (FILE *) 0, *ic_out = (FILE *) 0;

typedef int yy_state_type;

extern int ic_lineno;

int ic_lineno = 1;

extern char *ic_text;
#define yytext_ptr ic_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ic_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ic_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[267] =
    {   0,
        0,    0,  101,  101,    0,    0,   95,   95,   95,   95,
       95,   95,    0,    0,    0,    0,  107,  105,    8,    9,
        7,   74,  105,   96,  105,   68,   76,   47,   48,   66,
       64,   63,   65,   62,   67,   43,   43,   53,   54,   58,
       55,   60,   41,   49,   50,   77,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   51,   75,   52,   73,    8,    7,   90,  101,  102,
      106,  106,   95,   91,   94,  106,   93,    3,    5,    4,
       97,   98,    7,   57,    0,   46,    0,  104,   99,   86,
       79,   87,   84,   69,   82,   70,   83,    1,    0,   85,

       42,   43,    0,    0,   72,   59,   56,   61,   71,   41,
       88,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   26,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   12,   41,   41,   41,   41,   89,
       78,    0,   90,    7,    0,  101,    0,  100,   95,   91,
        0,   92,   93,    3,    2,    0,  103,    0,    0,    6,
       42,   45,   44,   81,   80,   41,   22,   41,   41,   41,
       41,   41,   41,   41,   41,   28,   41,   33,   41,   41,
       41,   41,   24,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,    0,   41,   40,   32,   41,   41,   27,

       41,   41,   41,   41,   35,   41,   41,   41,   41,   41,
       41,   41,   41,   14,   41,   29,   41,   41,   31,    0,
       41,   25,   41,   41,   30,   36,   41,   41,   41,   41,
       34,   41,   41,   13,   11,   41,   41,   41,   90,   16,
       37,   41,   41,   41,   41,   41,   38,   18,   41,   41,
       20,   23,   41,   17,   10,   41,   15,   41,   41,   21,
       39,   41,   41,   41,   19,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,    1,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   27,   27,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       29,   30,   31,   32,   28,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   28,   28,   42,   43,   44,
       45,   46,   28,   47,   48,   49,   50,   51,   28,   52,
       53,   54,   55,   56,   57,   58,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    4,    5,    1,    6,
        1,    1,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[281] =
    {   0,
        0,   57,   57,   59,    0,    0,   64,   67,   70,   75,
       87,   90,   67,   92,  391,  390,  392,  395,  395,  395,
      387,  365,  383,  395,   93,  363,   72,  395,  395,  362,
       88,  395,   87,  395,  101,  101,  108,  395,  395,   74,
      361,   90,    0,  395,  395,  360,  349,   59,   90,  338,
       89,  101,  329,   79,  336,   91,  343,   99,  100,  335,
      105,  395,  112,  395,  395,  147,  153,  336,  369,  395,
      368,  395,  154,  142,  395,  369,  145,    0,  395,  356,
      395,  395,  369,  395,  366,  395,  164,  395,  395,  395,
      395,  395,  395,  395,  395,  395,  395,  395,  368,  395,

      150,  156,  159,    0,  345,  395,  395,  395,  344,    0,
      395,  319,  318,  321,  332,  327,  313,  314,  328,  318,
      314,  311,  311,    0,  307,  311,  306,  308,  313,  302,
      305,  105,   30,  306,    0,  298,  299,  311,  304,  395,
      395,  178,  302,  179,  302,  334,  333,  395,  185,  171,
      334,  395,  174,    0,  395,  193,  395,  336,  335,  395,
      178,  183,    0,  395,  395,  296,    0,  294,  288,  301,
      299,  295,  297,  282,  296,    0,  291,    0,  288,  278,
      290,  283,    0,  276,  278,  284,  157,  274,  282,  281,
      276,  267,  279,  270,  262,    0,    0,  268,  269,    0,

      268,  272,  259,  260,    0,  265,  268,  256,  254,  265,
      256,  251,  262,    0,  253,    0,  258,  251,    0,  258,
      257,    0,  256,  255,    0,    0,  245,  239,  241,  239,
        0,  251,  248,    0,    0,  235,  240,  236,  395,    0,
        0,  246,  234,  243,  231,  220,    0,    0,  207,  214,
        0,    0,  200,    0,    0,  185,    0,  169,  165,    0,
        0,  151,  136,  126,    0,  395,  206,  212,  218,  224,
      230,  235,  238,  243,  249,  254,  260,  266,  148,  272
    } ;

static yyconst flex_int16_t yy_def[281] =
    {   0,
      266,    1,  267,  267,  268,  268,  268,  268,  268,  268,
      268,  268,  269,  269,  270,  270,  266,  266,  266,  266,
      266,  266,  271,  266,  272,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  273,  266,  266,  266,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  266,  266,  266,  266,  266,  266,  266,  274,  266,
      274,  266,  266,  266,  266,  275,  266,  276,  266,  266,
      266,  266,  266,  266,  271,  266,  277,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  278,  266,

      266,  266,  266,  279,  266,  266,  266,  266,  266,  273,
      266,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  266,
      266,  266,  266,  266,  266,  274,  274,  266,  266,  266,
      275,  266,  266,  276,  266,  277,  266,  280,  278,  266,
      266,  266,  279,  266,  266,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  266,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  266,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  266,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,    0,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266
    } ;

static yyconst flex_int16_t yy_nxt[454] =
    {   0,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       37,   38,   39,   40,   41,   42,   43,   43,   44,   18,
       45,   46,   47,   48,   49,   50,   51,   52,   43,   53,
       54,   55,   43,   43,   43,   56,   57,   58,   59,   60,
       61,   43,   43,   43,   62,   63,   64,   65,   66,   70,
       67,   70,  187,   68,   71,   73,   71,   73,   73,   79,
       73,   73,   75,   73,  188,   76,   73,   75,   73,   80,
       76,   91,   74,   74,   74,   74,   74,   74,   73,   75,
       73,   73,   75,   73,   79,   88,   92,  105,  106,  113,

       89,   94,   96,  114,   80,   77,   77,   77,   77,   77,
       77,   97,   95,   98,  108,  109,  124,  101,   99,  102,
      102,  102,  125,  127,  101,  100,  102,  102,  102,  115,
      118,  116,  119,  120,  103,  130,  140,  128,  131,  132,
      134,  138,  121,  185,  135,  122,  136,  133,  142,  139,
      142,  163,  104,  143,  142,  149,  144,  149,  186,  143,
      150,  150,  150,  153,  153,  153,  157,  141,  161,  161,
      161,  158,  101,  265,  102,  102,  102,  162,  162,  142,
      142,  142,  144,  264,  143,  143,  149,  263,  149,  150,
      150,  150,  153,  153,  153,  157,  161,  161,  161,  262,

      158,  162,  162,  212,  261,  213,   69,   69,   69,   69,
       69,   69,   72,   72,   72,   72,   72,   72,   78,   78,
       78,   78,   78,   78,   81,   81,   81,   81,   81,   81,
       85,  260,   85,   85,   85,   87,   87,   87,   87,   87,
       87,  110,  110,  146,  259,  146,  146,  146,  146,  151,
      258,  151,  151,  151,  154,  257,  256,  154,  154,  154,
      156,  156,  156,  156,  156,  156,  159,  159,  159,  159,
      159,  159,  158,  158,  158,  158,  158,  158,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,

      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  160,  157,  152,
      266,  147,  194,  145,  193,  192,  191,  190,  189,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      160,   86,   83,  155,  152,  148,  147,  145,  137,  129,
      126,  123,  117,  112,  111,  107,   93,   90,   86,   84,
       83,  266,   82,   82,   17,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266
    } ;

static yyconst flex_int16_t yy_chk[454] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    4,  133,    2,    3,    7,    4,    7,    8,   13,
        8,    9,    9,    9,  133,    9,   10,   10,   10,   13,
       10,   27,    7,    7,    7,    8,    8,    8,   11,   11,
       11,   12,   12,   12,   14,   25,   27,   40,   40,   48,

       25,   31,   33,   48,   14,   11,   11,   11,   12,   12,
       12,   33,   31,   35,   42,   42,   54,   36,   35,   36,
       36,   36,   54,   56,   37,   35,   37,   37,   37,   49,
       51,   49,   51,   52,   36,   58,   63,   56,   58,   58,
       59,   61,   52,  132,   59,   52,   59,   58,   66,   61,
       66,  279,   36,   66,   67,   73,   67,   73,  132,   67,
       74,   74,   74,   77,   77,   77,   87,   63,  101,  101,
      101,   87,  102,  264,  102,  102,  102,  103,  103,  142,
      144,  142,  144,  263,  142,  144,  149,  262,  149,  150,
      150,  150,  153,  153,  153,  156,  161,  161,  161,  259,

      156,  162,  162,  187,  258,  187,  267,  267,  267,  267,
      267,  267,  268,  268,  268,  268,  268,  268,  269,  269,
      269,  269,  269,  269,  270,  270,  270,  270,  270,  270,
      271,  256,  271,  271,  271,  272,  272,  272,  272,  272,
      272,  273,  273,  274,  253,  274,  274,  274,  274,  275,
      250,  275,  275,  275,  276,  249,  246,  276,  276,  276,
      277,  277,  277,  277,  277,  277,  278,  278,  278,  278,
      278,  278,  280,  280,  280,  280,  280,  280,  245,  244,
      243,  242,  238,  237,  236,  233,  232,  230,  229,  228,
      227,  224,  223,  221,  220,  218,  217,  215,  213,  212,

      211,  210,  209,  208,  207,  206,  204,  203,  202,  201,
      199,  198,  195,  194,  193,  192,  191,  190,  189,  188,
      186,  185,  184,  182,  181,  180,  179,  177,  175,  174,
      173,  172,  171,  170,  169,  168,  166,  159,  158,  151,
      147,  146,  145,  143,  139,  138,  137,  136,  134,  131,
      130,  129,  128,  127,  126,  125,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  114,  113,  112,  109,  105,
       99,   85,   83,   80,   76,   71,   69,   68,   60,   57,
       55,   53,   50,   47,   46,   41,   30,   26,   23,   22,
       21,   17,   16,   15,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ic__flex_debug;
int ic__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ic_text;
#line 1 "tokens.l"
#line 2 "tokens.l"
#include <string>
#include "iCProgram.h"
#include "iCScope.h" 
#include "ParserContext.h"
#include "iCIdentifier.h"
#include "iCProcess.h"
#include "iCState.h"
#include "CCode.h"
#include "iCTimeout.h"
#include "iCHyperprocess.h"

#include "parser.hpp"

#define SAVE_TOKEN ic_lval.string = new std::string(ic_text, ic_leng)
#define TOKEN(t) (ic_lval.token = t)
extern "C" int ic_wrap() { }
extern ParserContext* parser_context;

const int IC_TAB_SIZE = 4;

#define YY_USER_ACTION parser_context->inc_column(ic_leng);








#line 689 "tokens.cpp"

#define INITIAL 0
#define C_CODE 1
#define PREPROCESSOR 2
#define LM_LINENUM 3
#define LM_FILE 4
#define LM_FLAGS 5
#define COMMENT 6
#define SKIP_TO_NEWLINE 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ic_lex_destroy (void );

int ic_get_debug (void );

void ic_set_debug (int debug_flag  );

YY_EXTRA_TYPE ic_get_extra (void );

void ic_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *ic_get_in (void );

void ic_set_in  (FILE * in_str  );

FILE *ic_get_out (void );

void ic_set_out  (FILE * out_str  );

yy_size_t ic_get_leng (void );

char *ic_get_text (void );

int ic_get_lineno (void );

void ic_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ic_wrap (void );
#else
extern int ic_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( ic_text, ic_leng, 1, ic_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ic_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ic_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ic_in))==0 && ferror(ic_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ic_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ic_lex (void);

#define YY_DECL int ic_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ic_text and ic_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( ic_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(ic_text[ic_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "tokens.l"

#line 883 "tokens.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ic_in )
			ic_in = stdin;

		if ( ! ic_out )
			ic_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ic_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ic__create_buffer(ic_in,YY_BUF_SIZE );
		}

		ic__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ic_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 267 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 395 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "tokens.l"
BEGIN(COMMENT);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "tokens.l"
BEGIN(INITIAL);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "tokens.l"
{
							SAVE_TOKEN;
							std::string* str = ic_lval.string;
							//std::cout<<"comment line \""<<*str<<"\""<<std::endl;
							return TCOMMENTLINE;
						}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "tokens.l"

	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 48 "tokens.l"
parser_context->inc_line_num();           		
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 50 "tokens.l"
{
							SAVE_TOKEN;
							std::string* str = ic_lval.string;
							str->erase(0, 2); // trim the dollar sign
							str->erase(str->end()-1, str->end()); // trim the newline
							//std::cout<<"comment line \""<<*str<<"\""<<std::endl;
							return TCOMMENTLINE;
						}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "tokens.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "tokens.l"
{parser_context->to_prev_column(); parser_context->tab_column(IC_TAB_SIZE);}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 60 "tokens.l"
parser_context->inc_line_num(); 	
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "tokens.l"
return TOKEN(TPROC			);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "tokens.l"
return TOKEN(TSTATE			);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "tokens.l"
return TOKEN(TTO			);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "tokens.l"
return TOKEN(TSTART			);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "tokens.l"
return TOKEN(TSTOP			);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "tokens.l"
return TOKEN(TTIMEOUT		);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "tokens.l"
return TOKEN(TACTIVE		);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "tokens.l"
return TOKEN(TPASSIVE		);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "tokens.l"
return TOKEN(TSIZEOF		);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "tokens.l"
return TOKEN(THYPERPROCESS	);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "tokens.l"
return TOKEN(TVECTOR		);	
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "tokens.l"
return TOKEN(TREGISTER		);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "tokens.l"
return TOKEN(TBIT			);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "tokens.l"
return TOKEN(TENABLED		);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "tokens.l"
return TOKEN(TSET			);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "tokens.l"
return TOKEN(TCLEAN			);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "tokens.l"
return TOKEN(TIF			);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "tokens.l"
return TOKEN(TELSE			);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "tokens.l"
return TOKEN(TFOR			);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 82 "tokens.l"
return TOKEN(TTRUE			);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 83 "tokens.l"
return TOKEN(TFALSE	 		);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 85 "tokens.l"
SAVE_TOKEN; return TVOID	 ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 86 "tokens.l"
SAVE_TOKEN; return TCHAR	 ;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 87 "tokens.l"
SAVE_TOKEN; return TINT		 ;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 88 "tokens.l"
SAVE_TOKEN; return TSHORT	 ;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 89 "tokens.l"
SAVE_TOKEN; return TLONG	 ;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 90 "tokens.l"
SAVE_TOKEN; return TFLT		 ;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "tokens.l"
SAVE_TOKEN; return TDBL		 ;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 92 "tokens.l"
SAVE_TOKEN; return TSGND	 ;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 93 "tokens.l"
SAVE_TOKEN; return TUNSGND	 ;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 94 "tokens.l"
SAVE_TOKEN; return TBOOL	 ;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 98 "tokens.l"
SAVE_TOKEN; return TIDENTIFIER	;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 99 "tokens.l"
SAVE_TOKEN; return TDCONST		;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 100 "tokens.l"
{SAVE_TOKEN; return TICONST;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 101 "tokens.l"
{SAVE_TOKEN; return THCONST;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "tokens.l"
{SAVE_TOKEN; return TBCONST;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 103 "tokens.l"
{SAVE_TOKEN; return TSTRING;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 105 "tokens.l"
return TOKEN(TLPAREN);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 106 "tokens.l"
return TOKEN(TRPAREN);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 107 "tokens.l"
return TOKEN(TLBRCKT);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 108 "tokens.l"
return TOKEN(TRBRCKT);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 109 "tokens.l"
return TOKEN(TLBRACE);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 110 "tokens.l"
return TOKEN(TRBRACE);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 111 "tokens.l"
return TOKEN(TCOLON);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "tokens.l"
return TOKEN(TSEMIC	);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 113 "tokens.l"
SAVE_TOKEN; return TASSGN	;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 114 "tokens.l"
SAVE_TOKEN; return TEQ		;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 115 "tokens.l"
SAVE_TOKEN; return TNEQ		;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 116 "tokens.l"
SAVE_TOKEN; return TLT		;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 117 "tokens.l"
SAVE_TOKEN; return TLE		;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "tokens.l"
SAVE_TOKEN; return TGT		;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "tokens.l"
SAVE_TOKEN; return TGE		;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 120 "tokens.l"
SAVE_TOKEN; return TDOT		;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 "tokens.l"
SAVE_TOKEN; return TCOMMA	;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 122 "tokens.l"
SAVE_TOKEN; return TPLUS	;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 123 "tokens.l"
SAVE_TOKEN; return TMINUS	;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 124 "tokens.l"
SAVE_TOKEN; return TMUL		;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 125 "tokens.l"
SAVE_TOKEN; return TDIV		;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 126 "tokens.l"
SAVE_TOKEN; return TPERC	;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 127 "tokens.l"
SAVE_TOKEN; return TINC		;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 128 "tokens.l"
SAVE_TOKEN; return TDEC		;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 129 "tokens.l"
SAVE_TOKEN; return TRSHIFT	;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 130 "tokens.l"
SAVE_TOKEN; return TLSHIFT	;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 131 "tokens.l"
SAVE_TOKEN; return TTILDE	;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 132 "tokens.l"
SAVE_TOKEN; return TEXCLAM	;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 133 "tokens.l"
SAVE_TOKEN; return TOR		;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 134 "tokens.l"
SAVE_TOKEN; return TAND		;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 135 "tokens.l"
SAVE_TOKEN; return TXOR		;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 136 "tokens.l"
SAVE_TOKEN; return TLOR		;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 137 "tokens.l"
SAVE_TOKEN; return TLAND	;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 138 "tokens.l"
SAVE_TOKEN; return TR_ASSGN	;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 139 "tokens.l"
SAVE_TOKEN; return TL_ASSGN	;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 140 "tokens.l"
SAVE_TOKEN; return TPLUS_ASSGN	;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 141 "tokens.l"
SAVE_TOKEN; return TMINUS_ASSGN	;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 142 "tokens.l"
SAVE_TOKEN; return TMUL_ASSGN	;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 143 "tokens.l"
SAVE_TOKEN; return TDIV_ASSGN	;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 144 "tokens.l"
SAVE_TOKEN; return TPERC_ASSGN	;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 145 "tokens.l"
SAVE_TOKEN; return TAND_ASSGN	;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 146 "tokens.l"
SAVE_TOKEN; return TXOR_ASSGN	;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 147 "tokens.l"
SAVE_TOKEN; return TOR_ASSGN	;
	YY_BREAK



case 90:
YY_RULE_SETUP
#line 152 "tokens.l"
BEGIN(LM_LINENUM);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 153 "tokens.l"
{
										parser_context->set_line(atoi(ic_text)); 
										parser_context->reset_column(); 
										BEGIN(LM_FILE);
									}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 158 "tokens.l"
{
										std::string* str = new std::string(ic_text, ic_leng);
										str->erase(0, 1); // trim the starting quote
										str->erase(str->end()-1, str->end()); // trim the ending quote
										parser_context->set_file(*str);
										delete str; 
										BEGIN(LM_FLAGS);
									}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 166 "tokens.l"
;
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 167 "tokens.l"
BEGIN(INITIAL);
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 168 "tokens.l"
;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 170 "tokens.l"
parser_context->err_msg("stray # in program"); BEGIN(SKIP_TO_NEWLINE);
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 171 "tokens.l"
;
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 172 "tokens.l"
BEGIN(INITIAL);
	YY_BREAK



case 99:
YY_RULE_SETUP
#line 177 "tokens.l"
BEGIN(C_CODE); ic_lval.string = new std::string;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 178 "tokens.l"
BEGIN(INITIAL); return TCCODEEXPR;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 179 "tokens.l"
/*SAVE_TOKEN; return TCCODELINE;*/(*ic_lval.string)+=" "+std::string(ic_text);
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 180 "tokens.l"
parser_context->inc_line_num();	
	YY_BREAK



case 103:
/* rule 103 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up ic_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up ic_text again */
YY_RULE_SETUP
#line 185 "tokens.l"
{
								SAVE_TOKEN;
								std::string* str = ic_lval.string;
								//parser_context->err_msg("adding c code line %s", str->c_str());
								str->erase(0, 1); // trim the dollar sign
								//str->erase(str->end()-1, str->end()); // trim the newline
								//parser_context->inc_line_num();
								return TCCODELINE;
							}
	YY_BREAK
case 104:
/* rule 104 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up ic_text */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up ic_text again */
YY_RULE_SETUP
#line 194 "tokens.l"
/*parser_context->inc_line_num();*/
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 199 "tokens.l"
printf("Unknown token!\n"); yyterminate();
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 201 "tokens.l"
ECHO;
	YY_BREAK
#line 1551 "tokens.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(C_CODE):
case YY_STATE_EOF(PREPROCESSOR):
case YY_STATE_EOF(LM_LINENUM):
case YY_STATE_EOF(LM_FILE):
case YY_STATE_EOF(LM_FLAGS):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(SKIP_TO_NEWLINE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ic_in at a new source and called
			 * ic_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ic_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ic_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ic_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of ic_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ic_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ic_restart(ic_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ic_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 267 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 267 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 266);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up ic_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ic_restart(ic_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ic_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ic_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ic_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ic_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ic__create_buffer(ic_in,YY_BUF_SIZE );
	}

	ic__init_buffer(YY_CURRENT_BUFFER,input_file );
	ic__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ic__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ic_pop_buffer_state();
	 *		ic_push_buffer_state(new_buffer);
     */
	ic_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ic__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ic_wrap()) processing, but the only time this flag
	 * is looked at is after ic_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ic__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ic_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ic__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ic_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ic__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ic_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ic__create_buffer()" );

	b->yy_is_our_buffer = 1;

	ic__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ic__create_buffer()
 * 
 */
    void ic__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ic_free((void *) b->yy_ch_buf  );

	ic_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ic_restart() or at EOF.
 */
    static void ic__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ic__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ic__init_buffer was _probably_
     * called from ic_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ic__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ic__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ic_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ic_ensure_buffer_stack();

	/* This block is copied from ic__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ic__switch_to_buffer. */
	ic__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ic_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ic__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ic__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ic_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ic_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ic_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ic_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ic_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ic__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ic_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ic__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ic__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ic_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ic__scan_bytes() instead.
 */
YY_BUFFER_STATE ic__scan_string (yyconst char * yystr )
{
    
	return ic__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ic_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ic__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ic_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ic__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ic__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ic__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ic_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ic_text[ic_leng] = (yy_hold_char); \
		(yy_c_buf_p) = ic_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ic_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ic_get_lineno  (void)
{
        
    return ic_lineno;
}

/** Get the input stream.
 * 
 */
FILE *ic_get_in  (void)
{
        return ic_in;
}

/** Get the output stream.
 * 
 */
FILE *ic_get_out  (void)
{
        return ic_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t ic_get_leng  (void)
{
        return ic_leng;
}

/** Get the current token.
 * 
 */

char *ic_get_text  (void)
{
        return ic_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ic_set_lineno (int  line_number )
{
    
    ic_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ic__switch_to_buffer
 */
void ic_set_in (FILE *  in_str )
{
        ic_in = in_str ;
}

void ic_set_out (FILE *  out_str )
{
        ic_out = out_str ;
}

int ic_get_debug  (void)
{
        return ic__flex_debug;
}

void ic_set_debug (int  bdebug )
{
        ic__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ic_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ic_in = stdin;
    ic_out = stdout;
#else
    ic_in = (FILE *) 0;
    ic_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ic_lex_init()
     */
    return 0;
}

/* ic_lex_destroy is for both reentrant and non-reentrant scanners. */
int ic_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ic__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ic_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	ic_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ic_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ic_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *ic_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ic_free (void * ptr )
{
	free( (char *) ptr );	/* see ic_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "tokens.l"




